import Visa from "@/components/visa/Visa";
import { VisaType } from "@/utils/interface";

export default async function Page() {
//   const visaTypes: VisaType[] = [
//     {
//       id: 22,
//       documentId: "x1cbqlyb2v0bkn5y33xt72ym",
//       name: "Student Visa",
//       description:
//         "For international students looking to pursue education abroad.",
//       key: null,
//       createdAt: "2025-06-20T22:10:12.395Z",
//       updatedAt: "2025-07-10T19:30:26.082Z",
//       publishedAt: "2025-07-10T19:30:26.103Z",
//       order: 1,
//       visas: [
//         {
//           id: 20,
//           documentId: "l1yzpxzpqwz5jhie8abecu1c",
//           title: "Student Visa (Subclass 400)",
//           subtitle:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas",
//           description:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas Ornare Molestie Dignissim Morbi Euismod. Proin Aliquet Mollis Ultricies Mauris Urna Elit Tincidunt Bibendum. Nam Et Nunc Adipiscing Etiam Tellus.",
//           createdAt: "2025-07-04T21:14:09.986Z",
//           updatedAt: "2025-07-04T22:44:50.480Z",
//           publishedAt: "2025-07-04T22:44:50.502Z",
//         },
//         {
//           id: 21,
//           documentId: "huu9cykjmfdigoheqit485u3",
//           title: "Student Visa (Subclass 500)",
//           subtitle:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas",
//           description:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas Ornare Molestie Dignissim Morbi Euismod. Proin Aliquet Mollis Ultricies Mauris Urna Elit Tincidunt Bibendum. Nam Et Nunc Adipiscing Etiam Tellus.",
//           createdAt: "2025-07-04T00:18:20.550Z",
//           updatedAt: "2025-07-04T22:44:59.545Z",
//           publishedAt: "2025-07-04T22:44:59.570Z",
//         },
//       ],
//       visaTypeImage: {
//         id: 8,
//         documentId: "m5yxgr1u1c0kbh1hy28kvy76",
//         name: "sample.jpg",
//         alternativeText: null,
//         caption: null,
//         width: 1430,
//         height: 955,
//         formats: {
//           large: {
//             ext: ".jpg",
//             url: "/uploads/large_sample_a0f2a409a3.jpg",
//             hash: "large_sample_a0f2a409a3",
//             mime: "image/jpeg",
//             name: "large_sample.jpg",
//             path: null,
//             size: 145.33,
//             width: 1000,
//             height: 668,
//             sizeInBytes: 145327,
//           },
//           small: {
//             ext: ".jpg",
//             url: "/uploads/small_sample_a0f2a409a3.jpg",
//             hash: "small_sample_a0f2a409a3",
//             mime: "image/jpeg",
//             name: "small_sample.jpg",
//             path: null,
//             size: 40.15,
//             width: 500,
//             height: 334,
//             sizeInBytes: 40153,
//           },
//           medium: {
//             ext: ".jpg",
//             url: "/uploads/medium_sample_a0f2a409a3.jpg",
//             hash: "medium_sample_a0f2a409a3",
//             mime: "image/jpeg",
//             name: "medium_sample.jpg",
//             path: null,
//             size: 83.8,
//             width: 750,
//             height: 501,
//             sizeInBytes: 83802,
//           },
//           thumbnail: {
//             ext: ".jpg",
//             url: "/uploads/thumbnail_sample_a0f2a409a3.jpg",
//             hash: "thumbnail_sample_a0f2a409a3",
//             mime: "image/jpeg",
//             name: "thumbnail_sample.jpg",
//             path: null,
//             size: 10.87,
//             width: 234,
//             height: 156,
//             sizeInBytes: 10866,
//           },
//         },
//         hash: "sample_a0f2a409a3",
//         ext: ".jpg",
//         mime: "image/jpeg",
//         size: 315.05,
//         url: "/uploads/sample_a0f2a409a3.jpg",
//         previewUrl: null,
//         provider: "local",
//         provider_metadata: null,
//         createdAt: "2025-07-10T19:13:34.429Z",
//         updatedAt: "2025-07-10T19:13:34.429Z",
//         publishedAt: "2025-07-10T19:13:34.429Z",
//       },
//     },
//     {
//       id: 21,
//       documentId: "wwqty10yas93etv5emdaob2n",
//       name: "Family Visa",
//       description: "Reunite with your loved ones across borders.",
//       key: null,
//       createdAt: "2025-06-20T22:11:28.175Z",
//       updatedAt: "2025-07-10T19:30:17.815Z",
//       publishedAt: "2025-07-10T19:30:17.832Z",
//       order: 2,
//       visas: [
//         {
//           id: 13,
//           documentId: "g5q9a8j79mnm22akowd9j1kh",
//           title: "Family Visa",
//           subtitle:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas",
//           description:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas Ornare Molestie Dignissim Morbi Euismod. Proin Aliquet Mollis Ultricies Mauris Urna Elit Tincidunt Bibendum. Nam Et Nunc Adipiscing Etiam Tellus.",
//           createdAt: "2025-07-04T22:43:27.491Z",
//           updatedAt: "2025-07-04T22:43:44.971Z",
//           publishedAt: "2025-07-04T22:43:44.987Z",
//         },
//         {
//           id: 15,
//           documentId: "xjr6qbo8dmb76nrd48n2ya5a",
//           title: "Family Visa (400)",
//           subtitle:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas",
//           description:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas Ornare Molestie Dignissim Morbi Euismod. Proin Aliquet Mollis Ultricies Mauris Urna Elit Tincidunt Bibendum. Nam Et Nunc Adipiscing Etiam Tellus.",
//           createdAt: "2025-07-04T22:43:49.383Z",
//           updatedAt: "2025-07-04T22:43:55.459Z",
//           publishedAt: "2025-07-04T22:43:55.472Z",
//         },
//       ],
//       visaTypeImage: {
//         id: 10,
//         documentId: "lp7o7w2ur8rukp98v1i4fyb5",
//         name: "sample2.jpg",
//         alternativeText: null,
//         caption: null,
//         width: 600,
//         height: 450,
//         formats: {
//           small: {
//             ext: ".jpg",
//             url: "/uploads/small_sample2_a7fb6cafee.jpg",
//             hash: "small_sample2_a7fb6cafee",
//             mime: "image/jpeg",
//             name: "small_sample2.jpg",
//             path: null,
//             size: 281.83,
//             width: 500,
//             height: 375,
//             sizeInBytes: 281828,
//           },
//           thumbnail: {
//             ext: ".jpg",
//             url: "/uploads/thumbnail_sample2_a7fb6cafee.jpg",
//             hash: "thumbnail_sample2_a7fb6cafee",
//             mime: "image/jpeg",
//             name: "thumbnail_sample2.jpg",
//             path: null,
//             size: 63.6,
//             width: 208,
//             height: 156,
//             sizeInBytes: 63600,
//           },
//         },
//         hash: "sample2_a7fb6cafee",
//         ext: ".jpg",
//         mime: "image/jpeg",
//         size: 79.51,
//         url: "/uploads/sample2_a7fb6cafee.jpg",
//         previewUrl: null,
//         provider: "local",
//         provider_metadata: null,
//         createdAt: "2025-07-10T19:15:58.848Z",
//         updatedAt: "2025-07-10T19:15:58.848Z",
//         publishedAt: "2025-07-10T19:15:58.848Z",
//       },
//     },
//     {
//       id: 23,
//       documentId: "sendoh3k989sdbm99w3vnnjm",
//       name: "Tourist Visa",
//       description:
//         "Discover the world with a visa tailored for travel and tourism.",
//       key: null,
//       createdAt: "2025-06-20T22:12:03.466Z",
//       updatedAt: "2025-07-10T19:30:37.028Z",
//       publishedAt: "2025-07-10T19:30:37.046Z",
//       order: 3,
//       visas: [
//         {
//           id: 17,
//           documentId: "wyqcxuhpl2k19x6wzkj95wqn",
//           title: "Tourist Visa (100)",
//           subtitle:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas",
//           description:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas Ornare Molestie Dignissim Morbi Euismod. Proin Aliquet Mollis Ultricies Mauris Urna Elit Tincidunt Bibendum. Nam Et Nunc Adipiscing Etiam Tellus.",
//           createdAt: "2025-07-04T22:43:59.640Z",
//           updatedAt: "2025-07-04T22:44:18.694Z",
//           publishedAt: "2025-07-04T22:44:18.707Z",
//         },
//         {
//           id: 19,
//           documentId: "dvfdvdkfpbujvbgv8xib1ybb",
//           title: "Tourist Visa (200)",
//           subtitle:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas",
//           description:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas Ornare Molestie Dignissim Morbi Euismod. Proin Aliquet Mollis Ultricies Mauris Urna Elit Tincidunt Bibendum. Nam Et Nunc Adipiscing Etiam Tellus.",
//           createdAt: "2025-07-04T22:44:22.281Z",
//           updatedAt: "2025-07-04T22:44:25.444Z",
//           publishedAt: "2025-07-04T22:44:25.454Z",
//         },
//       ],
//       visaTypeImage: {
//         id: 10,
//         documentId: "lp7o7w2ur8rukp98v1i4fyb5",
//         name: "sample2.jpg",
//         alternativeText: null,
//         caption: null,
//         width: 600,
//         height: 450,
//         formats: {
//           small: {
//             ext: ".jpg",
//             url: "/uploads/small_sample2_a7fb6cafee.jpg",
//             hash: "small_sample2_a7fb6cafee",
//             mime: "image/jpeg",
//             name: "small_sample2.jpg",
//             path: null,
//             size: 281.83,
//             width: 500,
//             height: 375,
//             sizeInBytes: 281828,
//           },
//           thumbnail: {
//             ext: ".jpg",
//             url: "/uploads/thumbnail_sample2_a7fb6cafee.jpg",
//             hash: "thumbnail_sample2_a7fb6cafee",
//             mime: "image/jpeg",
//             name: "thumbnail_sample2.jpg",
//             path: null,
//             size: 63.6,
//             width: 208,
//             height: 156,
//             sizeInBytes: 63600,
//           },
//         },
//         hash: "sample2_a7fb6cafee",
//         ext: ".jpg",
//         mime: "image/jpeg",
//         size: 79.51,
//         url: "/uploads/sample2_a7fb6cafee.jpg",
//         previewUrl: null,
//         provider: "local",
//         provider_metadata: null,
//         createdAt: "2025-07-10T19:15:58.848Z",
//         updatedAt: "2025-07-10T19:15:58.848Z",
//         publishedAt: "2025-07-10T19:15:58.848Z",
//       },
//     },
//     {
//       id: 19,
//       documentId: "ziksw3m8u3fwhh629fxop09w",
//       name: "Business Visa ",
//       description:
//         "For professionals attending meetings, conferences, or short-term work.",
//       key: null,
//       createdAt: "2025-06-20T22:12:34.910Z",
//       updatedAt: "2025-07-10T12:36:39.940Z",
//       publishedAt: "2025-07-10T12:36:39.966Z",
//       order: 4,
//       visas: [
//         {
//           id: 27,
//           documentId: "comdoimb14rhe18qh9k036fz",
//           title: "Business Visa (3000)",
//           subtitle:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas",
//           description:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas Ornare Molestie Dignissim Morbi Euismod. Proin Aliquet Mollis Ultricies Mauris Urna Elit Tincidunt Bibendum. Nam Et Nunc Adipiscing Etiam Tellus.",
//           createdAt: "2025-07-04T22:53:58.413Z",
//           updatedAt: "2025-07-04T22:54:12.334Z",
//           publishedAt: "2025-07-04T22:54:12.359Z",
//         },
//       ],
//       visaTypeImage: {
//         id: 1,
//         documentId: "nmha0t2t1ky7839gsodwo3y6",
//         name: "client2.jpg",
//         alternativeText: null,
//         caption: null,
//         width: 1080,
//         height: 721,
//         formats: {
//           large: {
//             ext: ".jpg",
//             url: "/uploads/large_client2_8c47097707.jpg",
//             hash: "large_client2_8c47097707",
//             mime: "image/jpeg",
//             name: "large_client2.jpg",
//             path: null,
//             size: 43.96,
//             width: 1000,
//             height: 668,
//             sizeInBytes: 43961,
//           },
//           small: {
//             ext: ".jpg",
//             url: "/uploads/small_client2_8c47097707.jpg",
//             hash: "small_client2_8c47097707",
//             mime: "image/jpeg",
//             name: "small_client2.jpg",
//             path: null,
//             size: 15.18,
//             width: 500,
//             height: 334,
//             sizeInBytes: 15181,
//           },
//           medium: {
//             ext: ".jpg",
//             url: "/uploads/medium_client2_8c47097707.jpg",
//             hash: "medium_client2_8c47097707",
//             mime: "image/jpeg",
//             name: "medium_client2.jpg",
//             path: null,
//             size: 28.52,
//             width: 750,
//             height: 501,
//             sizeInBytes: 28522,
//           },
//           thumbnail: {
//             ext: ".jpg",
//             url: "/uploads/thumbnail_client2_8c47097707.jpg",
//             hash: "thumbnail_client2_8c47097707",
//             mime: "image/jpeg",
//             name: "thumbnail_client2.jpg",
//             path: null,
//             size: 4.84,
//             width: 234,
//             height: 156,
//             sizeInBytes: 4836,
//           },
//         },
//         hash: "client2_8c47097707",
//         ext: ".jpg",
//         mime: "image/jpeg",
//         size: 37.41,
//         url: "/uploads/client2_8c47097707.jpg",
//         previewUrl: null,
//         provider: "local",
//         provider_metadata: null,
//         createdAt: "2025-07-09T13:06:21.135Z",
//         updatedAt: "2025-07-10T12:33:26.392Z",
//         publishedAt: "2025-07-09T13:06:21.136Z",
//       },
//     },
//     {
//       id: 24,
//       documentId: "bqq4p0ipkhs6xcqid3lujlch",
//       name: "Work Visa",
//       description:
//         "Build your career internationally with a legal work permit.",
//       key: null,
//       createdAt: "2025-06-20T22:12:53.853Z",
//       updatedAt: "2025-07-10T19:30:45.099Z",
//       publishedAt: "2025-07-10T19:30:45.118Z",
//       order: 5,
//       visas: [
//         {
//           id: 23,
//           documentId: "o6dt7klr8ekjzi0fsj7jqwr8",
//           title: "Work Visa (200)",
//           subtitle:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas",
//           description:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas Ornare Molestie Dignissim Morbi Euismod. Proin Aliquet Mollis Ultricies Mauris Urna Elit Tincidunt Bibendum. Nam Et Nunc Adipiscing Etiam Tellus.",
//           createdAt: "2025-07-04T22:45:04.014Z",
//           updatedAt: "2025-07-04T22:45:19.619Z",
//           publishedAt: "2025-07-04T22:45:19.635Z",
//         },
//         {
//           id: 25,
//           documentId: "gzkz1tg1oionz32xq4m6ihpr",
//           title: "Work Visa (300)",
//           subtitle:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas",
//           description:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas Ornare Molestie Dignissim Morbi Euismod. Proin Aliquet Mollis Ultricies Mauris Urna Elit Tincidunt Bibendum. Nam Et Nunc Adipiscing Etiam Tellus.",
//           createdAt: "2025-07-04T22:45:24.327Z",
//           updatedAt: "2025-07-04T22:45:29.981Z",
//           publishedAt: "2025-07-04T22:45:29.990Z",
//         },
//       ],
//       visaTypeImage: {
//         id: 8,
//         documentId: "m5yxgr1u1c0kbh1hy28kvy76",
//         name: "sample.jpg",
//         alternativeText: null,
//         caption: null,
//         width: 1430,
//         height: 955,
//         formats: {
//           large: {
//             ext: ".jpg",
//             url: "/uploads/large_sample_a0f2a409a3.jpg",
//             hash: "large_sample_a0f2a409a3",
//             mime: "image/jpeg",
//             name: "large_sample.jpg",
//             path: null,
//             size: 145.33,
//             width: 1000,
//             height: 668,
//             sizeInBytes: 145327,
//           },
//           small: {
//             ext: ".jpg",
//             url: "/uploads/small_sample_a0f2a409a3.jpg",
//             hash: "small_sample_a0f2a409a3",
//             mime: "image/jpeg",
//             name: "small_sample.jpg",
//             path: null,
//             size: 40.15,
//             width: 500,
//             height: 334,
//             sizeInBytes: 40153,
//           },
//           medium: {
//             ext: ".jpg",
//             url: "/uploads/medium_sample_a0f2a409a3.jpg",
//             hash: "medium_sample_a0f2a409a3",
//             mime: "image/jpeg",
//             name: "medium_sample.jpg",
//             path: null,
//             size: 83.8,
//             width: 750,
//             height: 501,
//             sizeInBytes: 83802,
//           },
//           thumbnail: {
//             ext: ".jpg",
//             url: "/uploads/thumbnail_sample_a0f2a409a3.jpg",
//             hash: "thumbnail_sample_a0f2a409a3",
//             mime: "image/jpeg",
//             name: "thumbnail_sample.jpg",
//             path: null,
//             size: 10.87,
//             width: 234,
//             height: 156,
//             sizeInBytes: 10866,
//           },
//         },
//         hash: "sample_a0f2a409a3",
//         ext: ".jpg",
//         mime: "image/jpeg",
//         size: 315.05,
//         url: "/uploads/sample_a0f2a409a3.jpg",
//         previewUrl: null,
//         provider: "local",
//         provider_metadata: null,
//         createdAt: "2025-07-10T19:13:34.429Z",
//         updatedAt: "2025-07-10T19:13:34.429Z",
//         publishedAt: "2025-07-10T19:13:34.429Z",
//       },
//     },
//     {
//       id: 20,
//       documentId: "d9widgv3fx9i8yvtw1fmub27",
//       name: "Diplomatic Visa",
//       description: "Reserved for government officials and diplomatic missions.",
//       key: null,
//       createdAt: "2025-06-20T22:13:11.979Z",
//       updatedAt: "2025-07-10T19:30:11.271Z",
//       publishedAt: "2025-07-10T19:30:11.306Z",
//       order: 6,
//       visas: [
//         {
//           id: 9,
//           documentId: "zsiw5ircgzp7bme08klvaxv1",
//           title: "Diplomatic Visa (Subclass 400)",
//           subtitle:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas",
//           description:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas Ornare Molestie Dignissim Morbi Euismod. Proin Aliquet Mollis Ultricies Mauris Urna Elit Tincidunt Bibendum. Nam Et Nunc Adipiscing Etiam Tellus.",
//           createdAt: "2025-07-04T21:14:57.435Z",
//           updatedAt: "2025-07-04T21:15:19.795Z",
//           publishedAt: "2025-07-04T21:15:19.811Z",
//         },
//         {
//           id: 11,
//           documentId: "gykrwkvredgh0uf9xga8d0bn",
//           title: "Diplomatic Visa (Subclass 100)",
//           subtitle:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas",
//           description:
//             "Dignissim Mi Ac Luctus Ultrices Enim Nulla Volutpat Aliquam. Quis Egestas Egestas Ornare Molestie Dignissim Morbi Euismod. Proin Aliquet Mollis Ultricies Mauris Urna Elit Tincidunt Bibendum. Nam Et Nunc Adipiscing Etiam Tellus.",
//           createdAt: "2025-07-04T21:15:30.768Z",
//           updatedAt: "2025-07-04T21:15:37.540Z",
//           publishedAt: "2025-07-04T21:15:37.549Z",
//         },
//       ],
//       visaTypeImage: {
//         id: 11,
//         documentId: "ufk9341des9n51jc7srf3pmq",
//         name: "images12.jpeg",
//         alternativeText: null,
//         caption: null,
//         width: 310,
//         height: 163,
//         formats: {
//           thumbnail: {
//             ext: ".jpeg",
//             url: "/uploads/thumbnail_images12_3ae465edcd.jpeg",
//             hash: "thumbnail_images12_3ae465edcd",
//             mime: "image/jpeg",
//             name: "thumbnail_images12.jpeg",
//             path: null,
//             size: 8.58,
//             width: 245,
//             height: 129,
//             sizeInBytes: 8576,
//           },
//         },
//         hash: "images12_3ae465edcd",
//         ext: ".jpeg",
//         mime: "image/jpeg",
//         size: 10.88,
//         url: "/uploads/images12_3ae465edcd.jpeg",
//         previewUrl: null,
//         provider: "local",
//         provider_metadata: null,
//         createdAt: "2025-07-10T19:17:05.462Z",
//         updatedAt: "2025-07-10T19:17:05.462Z",
//         publishedAt: "2025-07-10T19:17:05.462Z",
//       },
//     },
//   ];
  const res = await fetch(
    "https://admin.migrateglobe.com/api/visa-types?populate=*&sort=order:asc"
  );
  const json = await res.json();
  const visaTypes: VisaType[] = json.data;

  return (
    <div className="container-1200">
      <Visa visaTypes={visaTypes} />
    </div>
  );
}
